version: '2'
services:
    fpquant-app:
        image: fpquant
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fpquant-mysql:3306/fpquant?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fpquant-mysql:
        extends:
            file: mysql.yml
            service: fpquant-mysql
